#!/usr/bin/env bash
# Reads repo-root .env and writes an Xcode xcconfig with the keys.
# xcconfig treats `//` as a comment, so we escape it as `/$()/`.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
OUT="$ROOT/app/RAlly/Config/Secrets.generated.xcconfig"

mkdir -p "$(dirname "$OUT")"

escape_xcconfig() {
  # Escape // so xcconfig does not treat the rest of the line as a comment.
  printf '%s' "$1" | sed 's#//#/$()/#g'
}

{
  echo "// Generated by scripts/gen-secrets.sh — do not edit, do not commit."
  echo ""
  if [[ -f "$ENV_FILE" ]]; then
    # shellcheck disable=SC1090
    set -a
    # Parse KEY=VALUE lines, ignore comments/blank.
    while IFS= read -r line || [[ -n "$line" ]]; do
      [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
      key="${line%%=*}"
      value="${line#*=}"
      key="$(echo "$key" | xargs)"
      [[ -z "$key" ]] && continue
      echo "${key} = $(escape_xcconfig "$value")"
    done < "$ENV_FILE"
    set +a
  else
    echo "ANTHROPIC_API_KEY = "
  fi
} > "$OUT"

echo "Wrote $OUT"
